# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: sudo curl https://github.com/gitpod-io/gitpod/releases/download/2022.09.1-rc0/gitpod-installer-linux-amd64 -Lo /usr/local/bin/gitpod-installer && sudo chmod +x /usr/local/bin/gitpod-installer
  - command: brew install yq
  - command: brew install kubectl