apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-certificates
  namespace: gitpod
  labels:
    app: gitpod
    component: gitpod-installer
spec:
  secretName: https-certificates
  issuerRef:
    name: 'letsencrypt-prod'
    kind: 'ClusterIssuer'
  dnsNames:
    - 'gitpod.central.dev.cloud.ilab-nlb.de'
    - '*.gitpod.central.dev.cloud.ilab-nlb.de'
    - '*.ws.gitpod.central.dev.cloud.ilab-nlb.de'
  secretTemplate:
    labels:
      app: gitpod
      component: gitpod-installer