---
# cert-manager.io/v1/Certificate ws-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ws-manager
  name: ws-manager
  namespace: gitpod
spec:
  dnsNames:
    - registry-facade
    - server
    - ws-manager-bridge
    - ws-proxy
    - ws-manager
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  secretName: ws-manager-client-tls
  secretTemplate:
    labels:
      app: gitpod
      component: ws-manager
status: {}
