---
# v1/Secret builtin-registry-auth
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRwb2QuZGV2b3BzLmh1Yi5jbG91ZC5pbGFiLW5sYi5kZSI6eyJhdXRoIjoiYWtwdVIxSkxhMHR4VUZsaGVEUmlURzFaWWpRNlpIVmpSM0pXVms5RVJrVlZSa2hoVjFjMWEyOD0ifX19
  password: ZHVjR3JWVk9ERkVVRkhhV1c1a28=
  user: akpuR1JLa0txUFlheDRiTG1ZYjQ=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: docker-registry
  name: builtin-registry-auth
  namespace: gitpod
type: kubernetes.io/dockerconfigjson
