---
# v1/Secret builtin-registry-auth
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRwb2QuZGV2b3BzLmh1Yi5jbG91ZC5pbGFiLW5sYi5kZSI6eyJhdXRoIjoiV0hCZlVuZ3dMazFNUkVaNlFVWXVjVnBuU25RNk4ycGxPVEpYWWkwM1Z5NVFVbXBKY0VNd2NVWT0ifX19
  password: N2plOTJXYi03Vy5QUmpJcEMwcUY=
  user: WHBfUngwLk1MREZ6QUYucVpnSnQ=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: docker-registry
  name: builtin-registry-auth
  namespace: gitpod
type: kubernetes.io/dockerconfigjson
