---
# v1/Secret builtin-registry-auth
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRwb2QuY2VudHJhbC5kZXYuY2xvdWQuaWxhYi1ubGIuZGUiOnsiYXV0aCI6Ilh6UkxVSGRsTjJoVWFGRkRiVVJEZURsR1oyazZOamsxWmxWWGRsRlJSRkZPV2toTlpESndkMDg9In19fQ==
  password: Njk1ZlVXdlFRRFFOWkhNZDJwd08=
  user: XzRLUHdlN2hUaFFDbURDeDlGZ2k=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: docker-registry
  name: builtin-registry-auth
  namespace: gitpod
type: kubernetes.io/dockerconfigjson
