---
# v1/Secret minio
# Source: minio/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "gitpod"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.6.3
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  root-user: "ZHZyZ0NTOGlMY0NWWHFxZHNlRVI="
  root-password: "Zm5kZ3M2a094SVU3ci0tc3M3VGE="
  key.json: ""
