---
# v1/Secret minio
# Source: minio/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "gitpod"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.6.3
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  root-user: "LTlnS3M2WC1ISFBzbjFCak5GOXY="
  root-password: "WGpoY2ZMV0xGM1VpT0UxbnVvY3A="
  key.json: ""
