---
# v1/Secret registry-secret
# Source: docker-registry/charts/docker-registry/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: gitpod
  labels:
    app: docker-registry
    chart: docker-registry-1.16.0
    heritage: Helm
    release: docker-registry
type: Opaque
data:
  haSharedSecret: "ZFdESVVtTE9RZ0tUZ1EwRg=="
  proxyUsername: ""
  proxyPassword: ""
