---
# v1/ConfigMap gitpod
apiVersion: v1
data:
  config.yaml: |
    apiVersion: v1
    authProviders: []
    blockNewUsers:
      enabled: false
      passlist: []
    certificate:
      kind: secret
      name: https-certificates
    containerRegistry:
      inCluster: true
      privateBaseImageAllowList: []
    database:
      inCluster: true
    disableDefinitelyGp: true
    domain: gitpod.central.dev.cloud.ilab-nlb.de
    kind: Full
    metadata:
      region: local
      shortname: default
    objectStorage:
      inCluster: true
      resources:
        requests:
          memory: 2Gi
    observability:
      logLevel: trace
    openVSX:
      url: https://open-vsx.org
    repository: eu.gcr.io/gitpod-core-dev/build
    sshGatewayHostKey:
      kind: secret
      name: ssh-gateway-host-key
    workspace:
      maxLifetime: 36h0m0s
      pvc:
        size: 10Gi
        snapshotClass: ""
        storageClass: ""
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
      runtime:
        containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
        containerdSocket: /run/containerd/containerd.sock
        fsShiftMethod: fuse
      timeoutDefault: 12h0m0s
  versions.json: |-
    {
      "versions": {
        "version": "release-2022.09.2.3",
        "components": {
          "agentSmith": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "blobserve": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "caUpdater": {
            "version": "commit-313e75e99d5db6f5ac4eb71ecc25b8807fdd8366"
          },
          "contentService": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "dashboard": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "dbMigrations": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "dbSync": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "ideProxy": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "ideMetrics": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "ideService": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "imageBuilder": {
            "version": ""
          },
          "imageBuilderMk3": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7",
            "builderImage": {
              "version": "cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
            }
          },
          "installationTelemetry": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "integrationTests": {
            "version": ""
          },
          "openVSXProxy": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "paymentEndpoint": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "proxy": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "public-api-server": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "registryFacade": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "server": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "serviceWaiter": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "usage": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "workspace": {
            "codeImage": {
              "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
            },
            "dockerUp": {
              "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
            },
            "supervisor": {
              "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
            },
            "workspacekit": {
              "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
            },
            "desktopIdeImages": {
              "codeDesktop": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "codeDesktopInsiders": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "intellij": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "intellijLatest": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7-latest"
              },
              "goland": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "golandLatest": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7-latest"
              },
              "pycharm": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "pycharmLatest": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7-latest"
              },
              "phpstorm": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "phpstormLatest": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7-latest"
              },
              "jbBackendPlugin": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "jbBackendPluginLatest": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7-latest"
              }
            }
          },
          "wsDaemon": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7",
            "userNamespaces": {
              "seccompProfileInstaller": {
                "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
              },
              "shiftfsModuleLoader": {
                "version": "commit-313e75e99d5db6f5ac4eb71ecc25b8807fdd8366"
              }
            }
          },
          "wsManager": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "wsManagerBridge": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          },
          "wsProxy": {
            "version": "commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7"
          }
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: gitpod
  name: gitpod
  namespace: gitpod
