---
# v1/ConfigMap ws-proxy
apiVersion: v1
data:
  config.json: |-
    {
      "ingress": {
        "httpAddress": "0.0.0.0:8080",
        "httpsAddress": "0.0.0.0:9090",
        "header": "x-wsproxy-host"
      },
      "proxy": {
        "https": {
          "key": "/mnt/certificates/tls.key",
          "crt": "/mnt/certificates/tls.crt"
        },
        "transportConfig": {
          "connectTimeout": "10s",
          "idleConnTimeout": "1m0s",
          "maxIdleConns": 0,
          "maxIdleConnsPerHost": 100
        },
        "blobServer": {
          "scheme": "https",
          "host": "ide.gitpod.devops.hub.cloud.ilab-nlb.de",
          "pathPrefix": "/blobserve"
        },
        "gitpodInstallation": {
          "scheme": "https",
          "hostName": "gitpod.devops.hub.cloud.ilab-nlb.de",
          "workspaceHostSuffix": ".ws.gitpod.devops.hub.cloud.ilab-nlb.de",
          "workspaceHostSuffixRegex": "\\.ws[^\\.]*\\.gitpod.devops.hub.cloud.ilab-nlb.de"
        },
        "workspacePodConfig": {
          "theiaPort": 23000,
          "supervisorPort": 22999,
          "supervisorImage": "eu.gcr.io/gitpod-core-dev/build/supervisor:commit-e0a1d0d8587a5253772b61aa6499d60177d9f415"
        },
        "builtinPages": {
          "location": "/app/public"
        }
      },
      "pprofAddr": "127.0.0.1:6060",
      "prometheusAddr": "127.0.0.1:9500",
      "readinessProbeAddr": ":8086",
      "namespace": "gitpod",
      "wsManager": {
        "addr": "ws-manager:8080",
        "tls": {
          "ca": "/ws-manager-client-tls-certs/ca.crt",
          "crt": "/ws-manager-client-tls-certs/tls.crt",
          "key": "/ws-manager-client-tls-certs/tls.key"
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ws-proxy
  name: ws-proxy
  namespace: gitpod
