---
# rbac.authorization.k8s.io/v1/ClusterRoleBinding gitpod-image-builder-mk3-proxy-kube-rbac-proxy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: image-builder-mk3
  name: gitpod-image-builder-mk3-proxy-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-kube-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: image-builder-mk3
    namespace: gitpod
