---
# rbac.authorization.k8s.io/v1/ClusterRoleBinding gitpod-registry-facade-rb
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: registry-facade
  name: gitpod-registry-facade-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-registry-facade
subjects:
  - kind: ServiceAccount
    name: registry-facade
    namespace: gitpod
