---
# rbac.authorization.k8s.io/v1/ClusterRoleBinding gitpod-server-rb-kube-rbac-proxy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: server
  name: gitpod-server-rb-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-kube-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: server
    namespace: gitpod
