---
# rbac.authorization.k8s.io/v1/ClusterRoleBinding gitpod-ws-daemon-rb
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ws-daemon
  name: gitpod-ws-daemon-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-ws-daemon
subjects:
  - kind: ServiceAccount
    name: ws-daemon
    namespace: gitpod
