---
# rbac.authorization.k8s.io/v1/ClusterRoleBinding ide-service
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ide-service
  name: ide-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ide-service
subjects:
  - kind: ServiceAccount
    name: ide-service
    namespace: gitpod
