---
# rbac.authorization.k8s.io/v1/Role agent-smith
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: agent-smith
  name: agent-smith
  namespace: gitpod
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - update
