---
# rbac.authorization.k8s.io/v1/RoleBinding ide-proxy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ide-proxy
  name: ide-proxy
  namespace: gitpod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitpod-ns-psp:restricted-root-user
subjects:
  - kind: ServiceAccount
    name: ide-proxy
