---
# v1/Service content-service
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: content-service
    kind: service
  name: content-service
  namespace: gitpod
spec:
  ports:
    - name: rpc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 9500
      protocol: TCP
      targetPort: 9500
  selector:
    app: gitpod
    component: content-service
  type: ClusterIP
status:
  loadBalancer: {}
