---
# v1/Service server
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: server
    kind: service
  name: server
  namespace: gitpod
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: metrics
      port: 9500
      protocol: TCP
      targetPort: 9500
    - name: install-admin
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: debug
      port: 6060
      protocol: TCP
      targetPort: 6060
    - name: debugnode
      port: 9229
      protocol: TCP
      targetPort: 9229
  selector:
    app: gitpod
    component: server
  type: ClusterIP
status:
  loadBalancer: {}
