---
# v1/Service ws-proxy
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ws-proxy
    kind: service
  name: ws-proxy
  namespace: gitpod
spec:
  ports:
    - name: http-proxy
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https-proxy
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: metrics
      port: 9500
      protocol: TCP
      targetPort: 9500
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 2200
  selector:
    app: gitpod
    component: ws-proxy
  type: ClusterIP
status:
  loadBalancer: {}
