---
# apps/v1/Deployment ide-metrics
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: ide-metrics
  name: ide-metrics
  namespace: gitpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpod
      component: ide-metrics
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gitpod.io/checksum_config: a5cf580644efed7767186c43588ee3aaec2b0c25ce14bb1861f7ddda87f8cb0d
      creationTimestamp: null
      labels:
        app: gitpod
        component: ide-metrics
      name: ide-metrics
      namespace: gitpod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gitpod.io/workload_meta
                    operator: Exists
      containers:
        - args:
            - run
            - --config
            - /config/config.json
          env:
            - name: GITPOD_DOMAIN
              value: gitpod.central.dev.cloud.ilab-nlb.de
            - name: GITPOD_INSTALLATION_SHORTNAME
              value: default
            - name: GITPOD_REGION
              value: local
            - name: HOST_URL
              value: https://gitpod.central.dev.cloud.ilab-nlb.de
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBE_DOMAIN
              value: svc.cluster.local
            - name: LOG_LEVEL
              value: trace
          image: eu.gcr.io/gitpod-core-dev/build/ide-metrics:commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7
          imagePullPolicy: IfNotPresent
          name: ide-metrics
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
        - args:
            - --logtostderr
            - --insecure-listen-address=[$(IP)]:9500
            - --upstream=http://127.0.0.1:9500/
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: quay.io/brancz/kube-rbac-proxy:v0.12.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 9500
              name: metrics
          resources:
            requests:
              cpu: 1m
              memory: 30Mi
          securityContext:
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      serviceAccountName: ide-metrics
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: ide-metrics
          name: config
status: {}
