---
# apps/v1/Deployment proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: proxy
  name: proxy
  namespace: gitpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpod
      component: proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gitpod.io/checksum_config: e035540b5b28bb6434c5527f2a492d83af63dee488e6356156ba3c3ee46f85c7
      creationTimestamp: null
      labels:
        app: gitpod
        component: proxy
      name: proxy
      namespace: gitpod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gitpod.io/workload_meta
                    operator: Exists
      containers:
        - args:
            - --logtostderr
            - --insecure-listen-address=[$(IP)]:9500
            - --upstream=http://127.0.0.1:9545/
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: quay.io/brancz/kube-rbac-proxy:v0.12.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 9500
              name: metrics
              protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 30Mi
          securityContext:
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
        - env:
            - name: GITPOD_DOMAIN
              value: gitpod.central.dev.cloud.ilab-nlb.de
            - name: GITPOD_INSTALLATION_SHORTNAME
              value: default
            - name: GITPOD_REGION
              value: local
            - name: HOST_URL
              value: https://gitpod.central.dev.cloud.ilab-nlb.de
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBE_DOMAIN
              value: svc.cluster.local
            - name: LOG_LEVEL
              value: trace
            - name: PROXY_DOMAIN
              value: gitpod.central.dev.cloud.ilab-nlb.de
          image: eu.gcr.io/gitpod-core-dev/build/proxy:commit-cf5a72cd19f33a8d4c7ccf0301adc936905194f7
          imagePullPolicy: IfNotPresent
          name: proxy
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 22
              name: ssh
              protocol: TCP
            - containerPort: 9500
              name: metrics
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /etc/caddy/vhosts
              name: vhosts
            - mountPath: /etc/caddy/certificates
              name: config-certificates
            - mountPath: /etc/caddy/registry-auth
              name: builtin-registry-auth
            - mountPath: /etc/caddy/registry-certs
              name: builtin-registry-certs
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w net.core.somaxconn=32768; sysctl -w net.ipv4.ip_local_port_range='1024 65000'
          image: docker.io/library/alpine:3.16
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      securityContext:
        runAsNonRoot: false
      serviceAccountName: proxy
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: proxy-config
          name: vhosts
        - name: config-certificates
          secret:
            secretName: https-certificates
        - name: builtin-registry-auth
          secret:
            secretName: builtin-registry-auth
        - name: builtin-registry-certs
          secret:
            secretName: builtin-registry-certs
status: {}
