---
# batch/v1/CronJob gitpod-telemetry
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    app: gitpod
    component: gitpod
  name: gitpod-telemetry
  namespace: gitpod
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: gitpod
        component: gitpod
      name: gitpod-telemetry
      namespace: gitpod
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: gitpod
            component: gitpod
          name: gitpod-telemetry
          namespace: gitpod
        spec:
          containers:
            - args:
                - send
              env:
                - name: GITPOD_INSTALLATION_VERSION
                  value: release-2022.09.1.2
                - name: GITPOD_INSTALLATION_PLATFORM
                  value: unknown
                - name: SERVER_URL
                  value: http://server.gitpod.svc.cluster.local:9000
              image: eu.gcr.io/gitpod-core-dev/build/installation-telemetry:commit-3073cfbd53d1f854de79dd87e4d0d6a9825da114
              imagePullPolicy: IfNotPresent
              name: gitpod-telemetry
              resources: {}
          enableServiceLinks: false
          initContainers:
            - args:
                - -v
                - database
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: mysql
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      key: port
                      name: mysql
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: mysql
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: mysql
                - name: DB_ENCRYPTION_KEYS
                  valueFrom:
                    secretKeyRef:
                      key: encryptionKeys
                      name: mysql
              image: eu.gcr.io/gitpod-core-dev/build/service-waiter:commit-3073cfbd53d1f854de79dd87e4d0d6a9825da114
              name: database-waiter
              resources: {}
              securityContext:
                privileged: false
                runAsUser: 31001
          restartPolicy: OnFailure
          serviceAccountName: gitpod
  schedule: '@daily'
  successfulJobsHistoryLimit: 3
status: {}
